// Root layout for the application. This file configures the global HTML
// structure and provides the sidebar + main content layout used by the
// Next.js App Router. It also injects a site font and wraps the app with
// the AuthProvider so pages can access authentication state.
import { Poppins } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import AuthProvider from "./auth/AuthProvider";
import Header from "./components/Header";
import LogoEditor from "./components/LogoEditor";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // Root HTML wrapper. The `poppins.variable` class is injected by
  // Next's font loader and sets the --font-poppins CSS variable used in
  // globals.css for consistent typography.
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <div className="min-h-screen flex bg-zinc-50 dark:bg-black">
          <aside className="w-64 shrink-0 bg-white dark:bg-[#0b0b0b] border-r border-gray-200 dark:border-zinc-800">
            <div className="px-6 py-6">
              <div className="mb-6">
                <div className="flex items-center gap-3">
                  <LogoEditor size={40} />
                  <div>
                    {/* Site title/name — clicking goes home */}
                    <Link href="/" className="text-sm font-semibold text-zinc-900 dark:text-zinc-50">Nasran Salaeh</Link>
                    <div className="text-xs text-zinc-500 dark:text-zinc-400">IT Support / Programmer</div>
                  </div>
                </div>
              </div>

              <nav aria-label="Main navigation">
                <ul className="space-y-2">
                  <li>
                    <Link href="/" className="block rounded px-3 py-2 text-sm font-medium text-zinc-700 hover:bg-zinc-100 dark:text-zinc-200 dark:hover:bg-zinc-900">Home</Link>
                  </li>
                  <li>
                    <Link href="/about" className="block rounded px-3 py-2 text-sm font-medium text-zinc-700 hover:bg-zinc-100 dark:text-zinc-200 dark:hover:bg-zinc-900">About</Link>
                  </li>
                  <li>
                    <Link href="/profile" className="block rounded px-3 py-2 text-sm font-medium text-zinc-700 hover:bg-zinc-100 dark:text-zinc-200 dark:hover:bg-zinc-900">Profile</Link>
                  </li>
                  <li>
                    <Link href="/review" className="flex items-center justify-between block rounded px-3 py-2 text-sm font-medium text-zinc-700 hover:bg-zinc-100 dark:text-zinc-200 dark:hover:bg-zinc-900">
                      <span>Review</span>
                      <span className="ml-2 inline-block text-xs bg-emerald-100 text-emerald-800 rounded-full px-2 py-0.5 dark:bg-emerald-900 dark:text-emerald-300 animate-pulse">New</span>
                    </Link>
                  </li>
                  <li>
                    <Link href="/contact" className="block rounded px-3 py-2 text-sm font-medium text-zinc-700 hover:bg-zinc-100 dark:text-zinc-200 dark:hover:bg-zinc-900">Contact</Link>
                  </li>
                </ul>
              </nav>
            </div>
          </aside>

          <div className="flex-1 min-w-0 flex flex-col">
            {/*
              AuthProvider wraps interactive parts of the app. It is a
              client component (uses localStorage) and provides `useAuth()`
              to children like Header for login/logout state.
            */}
            <AuthProvider>
              <Header />
              {/* Main content area — pb-28 ensures space above the container footer */}
              <main className="flex-1 overflow-auto pb-28">{children}</main>
            </AuthProvider>
          </div>
          
        </div>
      </body>
    </html>
  );
}
